name: flake8

on:
  push:
    branches:
      - main
    paths:
      - "sapporo/**"
      - "tests/**"
      - "setup.py"
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  flake8:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python3 -m pip install --progress-bar off -U pip setuptools wheel
          python3 -m pip install --progress-bar off -U .[tests]

      - name: Check with flake8
        run: |
          bash ./tests/lint_and_style_check/flake8.sh
